# Generated by Django 4.2.26 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.TextField(blank=True)),
                ('make', models.TextField(blank=True)),
                ('model', models.TextField(blank=True)),
                ('vehicle_year', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_accident', models.DateField(blank=True)),
                ('damage_type', models.CharField(choices=[('unknown', 'Unknown'), ('none', 'None'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='minor', max_length=10)),
                ('address_accident', models.PositiveIntegerField(blank=True)),
                ('vehicles', models.ManyToManyField(related_name='accidents', to='accident_analysis.vehicle')),
            ],
        ),
    ]
