# Generated by Django 4.2.26 on 2025-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicles',
        ),
    ]
