# Generated by Django 5.2.9 on 2025-12-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_analysis', '0002_rename_vehicle_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='address_accident',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='accidents',
            name='date_of_accident',
            field=models.DateField(),
        ),
    ]
